// AUTO-GENERATED by `env-manager ts` - do not edit
import { z } from 'zod';

const env = z
	.object({
		UI_URL: z.url(),
		SERVER_URL: z.url(),
		API_URL: z.url(),
		UI_PORT: z.coerce.number().int(),
		PORT: z.coerce.number().int(),
		SMOKE: z.stringbool(),
		SKIP_SERVER: z.stringbool(),
	})
	.parse(process.env);

export default env;
